language: c
os: osx
before_install: 
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
  - bash Miniconda3-latest-MacOSX-x86_64.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export LD_LIBRARY_PATH="$HOME/miniconda/lib:$LD_LIBRARY_PATH"
  - which conda
  - git clone git://github.com/ecell/ecell4-base && cd ecell4-base
  - git submodule init && git submodule update
  - conda install -y boost gsl hdf5 cmake
  - $HOME/miniconda/bin/python setup.py bdist_wheel
